<!DOCTYPE html>
<html>

<head>
    <title>Student Report Card</title>
    <style>
    body {
        font-family: 'DejaVu Sans', sans-serif;
        background-image: url('{{ $base64 }}');
        background-size: cover;
        background-repeat: no-repeat;
        padding: 30px;
        color: #000;
    }


    .report-header h1 {
        font-size: 24px;
        font-weight: bold;
        text-align: center;
    }

    .info h3 {
        font-size: 16px;
        margin: 5px 0;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 10px;
        background: rgba(255, 255, 255, 0.8);
    }

    th,
    td {
        border: 1px solid #333;
        padding: 8px;
        text-align: center;
    }

    .signature,
    .footer {
        margin-top: 20px;
        font-size: 14px;
        font-weight: bold;
    }

    .signature {
    text-align: right;
    margin-top: 20px;
    font-size: 14px;
}


    .footer {
        display: flex;
        justify-content: space-between;
    }
    </style>
</head>

<body>

    <div class="header">
        <h1>Report Card</h1>
        <p>Academic Session: {{ date('Y') }}</p>
    </div>

    <div class="info">
        <h3>Student Name: {{ $details->name ?? 'N/A' }}</h3>
        <h3>Class: {{ $details->hasClass->name ?? 'N/A' }}</h3>
        <h3>Roll Number: {{ $details->id ?? 'N/A' }}</h3>

    </div>

   <table>
        <thead>
            <tr>
                <th>Sl. No</th>
                <th>Subject</th>
                <th>Total Marks</th>
                <th>Obtained Marks</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data as $d)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>
                        {{-- If subject is stored as ID --}}
                        {{ \App\Models\AddSubject::find($d->subject)->name ?? 'N/A' }}
                        {{-- Or if already stored as name, just use: --}}
                        {{-- {{ $d->subject }} --}}
                    </td>
                    <td>{{ $d->total_marks }}</td>
                    <td>{{ $d->obtained_marks }}</td>
                    <td>{{ $d->grade }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature">
         <img src="{{ $signatureBase64 }}" alt="Signature" style="height: 50px;"><br>
        __________________________<br>
        Authorized Signature (Admin)
    </div>

    <div class="footer">
        <div>Date of Issue:
            {{ $data[0]->issued_at ? \Carbon\Carbon::parse($data[0]->issued_at)->format('d-m-Y') : now()->format('d-m-Y') }}
        </div>
        <div>Overall Evaluation: {{ $data[0]->result_status == 'Pass' ? 'Promoted' : 'Not Promoted' }}</div>
        <div>Generated by School Portal</div>
    </div>

</body>

</html>
